### ISSUE TITLE
Updated - [Important Information] Repository moved to a new home

### ISSUE THREAD

**Issue by 0llirocks** [0llirocks/cvss-suite#27]
Update: Friendly people agreed to transfer the repository instead of using my fork as the new home. This means that everything stays the same, except the repository now belongs to me.

~~# This gem moved to a new [home](https://github.com/0llirocks/cvss-suite)~~

~~## Why?~~
~~I (the maintainer) am no longer part of the GitHub organisation and therefore lost access to this repository.~~

~~## What does that mean?~~
~~- As a user of the gem it does not matter at all. The gem is still supported by the same person and will still receive updates.~~
~~- As a GitHub user who follows or watches this repository it probably means, that there won't be any new activity. Feel free to follow and fork the new repository.~~
~~- Since I am still following this repository I will notice issue reports and will react accordingly with changes to the gem (but in the new repository), but I highly recommend to open new issues directly in the new repository.~~

~~I hope we meet again on the other side~~ 😄

~~Best regards,~~
~~Oliver~~

**Comment by jan-kiszka** [comment]
Forking is less elegant than moving to a new namespace. What prevented the latter? Can we still help to resolve that? @fgreinacher

**Comment by 0llirocks** [comment]
@jan-kiszka I agree, a transfer to my personal account would also be an option. I already requested the detachment of my repo as a fork. Let me know if you want to transfer it to my personal account, I would probably need to remove my personal repo before accepting it.

**Comment by fgreinacher** [comment]
@0llirocks We recently introduced a new policy to ensure that only Siemens employees are members of the organization. I assume you are not with Siemens anymore, is that correct? 

If so (and if there is no other maintainer from Siemens) we should definitely move this repository and we should use GitHubs built-in functionality so that users get properly redirected to the new home.

If you're still with Siemens we can just add you back to the org.

**Comment by 0llirocks** [comment]
@fgreinacher Correct, I am no longer with Siemens and there is no other maintainer from Siemens. So I assume you will transfer the repo to my personal account? Let me know when you are planning the transfer since I need to delete/rename my fork to accept the transaction.

**Comment by fgreinacher** [comment]
@0llirocks Thanks for the quick answer and for still taking care of this!

I will transfer as soon as you're ready!

**Comment by 0llirocks** [comment]
@fgreinacher Ready, thanks for the transfer!

**Comment by fgreinacher** [comment]
@0llirocks It seems GitHub only allows moving a repo to your own namespace, so I just gave you admin permissions here. Please move on your own :)

**Comment by 0llirocks** [comment]
@fgreinacher It's disabled for the organisation: Organization members cannot transfer repositories
https://docs.github.com/en/organizations/managing-organization-settings/setting-permissions-for-deleting-or-transferring-repositories

**Comment by fgreinacher** [comment]
@0llirocks OMG, that's really complicated. I enabled this setting just now.

**Comment by 0llirocks** [comment]
@fgreinacher Thanks, I now have the permission to transfer it, but renaming my fork was not enough. I need to delete my repository. I will do it later in the day when I have more time to ensure that no data is lost. I will close the issue once I am done.

**Comment by fgreinacher** [comment]
OK, thanks!

**Comment by 0llirocks** [comment]
@fgreinacher I agree, I already requested the detachment of my fork, but it's not done yet (as far as I know only the GitHub support can detach forks). I will create a pull request for each branch and delete my repo, shouldn't be too complicated.

**Comment by 0llirocks** [comment]
@fgreinacher repo was successfully transferred, thanks for your help!
