### ISSUE TITLE
Compatibility with Ruby 3.4.0 and greater's enforcement of frozen string literals

### ISSUE THREAD

**Issue by rebelagentm** [0llirocks/cvss-suite#44]
### Subject of the issue
Ruby is moving towards enforcing frozen string literals.  Starting with Ruby 3.4.0-preview1, a deprecation warning is thrown if a string literal is mutated.  In 3.4.0-preview1, an option flag can be passed that will disable this.  Ruby 3.4 will become the stable release later this year.  Come Ruby 4, enforcing this will be a requirement without the option to disable.

We use this Gem at GitHub and will need this gem to be compatible with the frozen string literal enforcement before the end of this year.  I'm not sure of the extent of the work in this project, but I know that at least one place where we have encountered a warning is in this [method](https://github.com/0llirocks/cvss-suite/blob/master/lib/cvss_suite/cvss40/cvss40_calc_helper.rb#L354).

### Your environment
* cvss-suite: 3.2.1
* ruby: 3.4.0-preview1

### Steps to reproduce
Use the Gem and call the method `CvssSuite::Cvss40CalcHelper.concat_and_stringify`

### Expected behaviour
The Gem is compatible with the new behavior in Ruby

### Actual behaviour
A deprecation warning is thrown by Ruby 3.4.0-preview1

**Comment by 0llirocks** [comment]
@rebelagentm Thank you for this issue, I will make sure that the gem runs with newer ruby versions. Just let me clarify the ruby version you use. As far as I can tell, 3.4 is currently in preview and will be released this December. Ruby 4.0 (or whatever comes after 3.4) should be released in Dec 2025 or am I missing something?

You are testing with 3.4.preview right?

**Comment by rebelagentm** [comment]
@0llirocks Thank you for the quick response!

Sorry for the confusion!  You are correct.  Ruby 3.4 comes in December and Ruby 4 (or whatever comes after 3.4) won't be until December 2025.  I was getting my timelines mixed up.  3.4 is the first version to start warning about this.  That version still allows users to disable the frozen string literals via an option flag.  I think Ruby 4 is when it is planned to become the default without the option to disable it.

We are currently using 3.4-preview with the plan to use 3.4 starting in December.  We will not be disabling the frozen string literal requirement, hence the need for us to make sure the `cvss-suite` gem works with 3.4 before the end of the year.

I'll edit the body of this issue to make sure it accurately reflects this.

**Comment by rebelagentm** [comment]
@0llirocks You may have already seen it, but one of my co-workers opened a [PR](https://github.com/0llirocks/cvss-suite/pull/47) for this.  I wanted to bring it to your attention in case you had started working on this.

**Comment by 0llirocks** [comment]
@rebelagentm Hey, yes I already saw that PR. It am very thankful that your colleague fixed it. Currently I am very busy gardening so that's why I am currently not at my desk. But thank you for the reminder anyway. I will try to merge the pr as soon as possible but definitely before winter 😉

**Comment by rebelagentm** [comment]
@0llirocks Thanks so much!  Enjoy your gardening!

**Comment by 0llirocks** [comment]
Part of version 3.3.0.
