### ISSUE TITLE
 undefined method base_score error for CVSS 4.0 vector string

### ISSUE THREAD

**Issue by mpurusottamc** [0llirocks/cvss-suite#45]
I am trying to calculate score & severity for a CVSS 4.0 vector string and getting the below error:
```
 undefined method `base_score' for #<CvssSuite::Cvss40:0x0000000321f3f510
```

Here's the code:
```ruby
vector_string="CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:L/E:A/CR:M/IR:H/AR:L/MAV:A/MAC:H/MAT:P/MPR:L/MUI:P/MVC:L/MVI:L/MVA:L/MSC:L/MSI:H/MSA:S/S:P/AU:Y/R:U/V:C/RE:M/U:Green"
cvss = CvssSuite.new(vector_string)
```

I do see cvss object has overall_score. but, base_score, temporal_score and environmental_score throw the same error.

### Your environment
* version of cvss-suite gem - 3.2.2
* version of ruby - ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]

I was hoping it would return values for all score variables.

**Comment by mpurusottamc** [comment]
Please Ignore this. I found out the right way to use this. 🤦 

Now, i am accessing base score using `base` object. instead of accessing `base_score`.

Here's the revised code that works for me:
```ruby
base_score=cvss.base&.score
```

**Comment by 0llirocks** [comment]
Hello @mpurusottamc, this behavior is expected. CVSS 4 doesn't really differentiate between the different score anymore. In the end, there is only one score. Therefore [we decided](https://github.com/0llirocks/cvss-suite/pull/36#issuecomment-2091121873) to only provide the overall score. This behavior is also documented [here](https://github.com/0llirocks/cvss-suite/blob/master/CHANGES.md#320---2024-05-04) and [here (under scores)](https://github.com/0llirocks/cvss-suite?tab=readme-ov-file#usage).

Your solution does work, but maybe check the cvss version before reading the score and treat cvss => 4 differently.

**Comment by mpurusottamc** [comment]
@0llirocks Thanks for clarifying. I have added conditional code on my side to handle cvss4 differently vs others. I will do something similar to read only for overall_score vs all other types of score.

Appreciate your quick response.
